# Generated by Django 5.2.7 on 2025-10-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_login_users_options_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
